// 获取用户菜单
export const GET_APPLICATION_MENU = 'GET_APPLICATION_MENU';

// 设置选中的分类
export const SET_SELECT_INDUSTRYCLASS = 'SET_SELECT_INDUSTRYCLASS';

export const SET_DISABLE_SELECT_INDUSTRYOBJ = 'SET_DISABLE_SELECT_INDUSTRYOBJ';

// 设置选中的区域分类
export const SET_SELECT_REGIONOBJ = 'SET_SELECT_REGIONOBJ';

export const SET_DISABLE_SELECT_REGIONOBJ = 'SET_DISABLE_SELECT_REGIONOBJ';

// 设置选中的客户行业分类
export const SET_SELECT_CUSTOMER_INDUSTRY = 'SET_SELECT_CUSTOMER_INDUSTRY';

export const SET_DISABLE_SELECT_CUSTOMER_INDUSTRYOBJ = 'SET_DISABLE_SELECT_CUSTOMER_INDUSTRYOBJ';

// 增加客户关系
export const ADD_CUSTOMER_RELATIONS = 'ADD_CUSTOMER_RELATIONS';

export const SET_DISABLE_CUSTOMER_CONTACTS = 'SET_DISABLE_CUSTOMER_CONTACTS';

// 删除客户关系
export const DELETE_CUSTOMER_RELATIONS = 'DELETE_CUSTOMER_RELATIONS';

// 增加联系方式
export const ADD_CUSTOMER_CONTACT = 'ADD_CUSTOMER_CONTACT';

// 删除联系方式
export const DEL_CUSTOMER_CONTACT = 'DEL_CUSTOMER_CONTACT';

// 增加地址
export const ADD_ADDRESS = 'ADD_ADDRESS';

// 设置删除的地址数据
export const SET_DISABLE_ADDRESSES = 'SET_DISABLE_ADDRESSES';

// 删除地址
export const DEL_ADDRESS = 'DEL_ADDRESS';

// 增加账户
export const ADD_ACCOUNT = 'ADD_ACCOUNT';

// 设置删除的账户
export const SET_DISABLE_ACCOUNTS = 'SET_DISABLE_ACCOUNTS';
// 删除账户
export const DEL_ACCOUNT = 'DEL_ACCOUNT';

export const CLEAR_CREATE_STORE = 'CLEAR_CREATE_STORE';

export const SET_DISABLE_CUSTOMER_RELATIONS = 'SET_DISABLE_CUSTOMER_RELATIONS';

export const SET_OWNER_LIST = 'SET_OWNER_LIST';

export const SET_DIS_OWNER_LIST = 'SET_DIS_OWNER_LIST';

export const UPDATE_CUSTOMER_CONTACTS = 'UPDATE_CUSTOMER_CONTACTS';
